version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/pytest"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/python/web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
