name: Build ARM binaries

on:
  push:
    branches:
      - develop
      - main
    paths:
      - '.github/workflows/arm_cross_compile.yml'
      - '.github/workflows/build_code.yml'
      - 'cpp/**'
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - '.github/workflows/arm_cross_compile.yml'
      - '.github/workflows/build_code.yml'
      - 'cpp/**'

jobs:
  fullspec:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "FULLSPEC"

  standard:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "STANDARD"

  aibom:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "AIBOM"

  gamernium:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "GAMERNIUM"

  # The fullspec connection board is the most common
  debug-fullspec:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "FULLSPEC"
      debug-flag: true
