name: Build ARM binaries

on:
  workflow_dispatch:
  push:
    paths:
      - 'cpp/**'
      - '.github/workflows/build_code.yml'
      - '.github/workflows/arm_cross_compile.yml'
  pull_request:
    paths:
      - 'cpp/**'
      - '.github/workflows/build_code.yml'
      - '.github/workflows/arm_cross_compile.yml'
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - 'develop'
      - 'main'

jobs:
  fullspec:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "FULLSPEC"

  standard:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "STANDARD"

  aibom:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "AIBOM"

  gamernium:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "GAMERNIUM"

  # The fullspec connection board is the most common
  debug-fullspec:
    uses: PiSCSI/piscsi/.github/workflows/arm_cross_compile.yml@develop
    with:
      connect-type: "FULLSPEC"
      debug-flag: true
