# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the rpi_image_creation branch
  push:
    branches: [ rpi_image_creation ]
  pull_request:
    branches: [ rpi_image_creation ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RaSCSI
        uses: actions/checkout@v2
        with:
          path: RASCSI
      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout RaSCSI
        uses: actions/checkout@v2
        with:
          repository: erichelgeson/pi-gen
          path: pi-gen
      
      - name: Install cross compile toolchain
        run: sudo apt-get install gcc-8-arm-linux-gnueabihf g++-8-arm-linux-gnueabihf binutils-arm-linux-gnueabihf libspdlog-dev

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Runs a single command using the runners shell
      - name: List files
        run: ls -alh

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
